name: CI

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
      - name: Deploy to GitHub Pages
        permissions:
          id-token: write
          pages: write
        uses: actions/deploy-pages@v3