name: CI

on:
  push:
    branches:
      - master
      - feature*
      - feature-*
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install dependencies
#         run: npm ci
#       - name: Run build
#         run: npm run build
#       # - name: Check directories
#       #   run: pwd && ls -a
#       # - name: Check Sym links
#       #   run: find out -type l && find out -type l
#       # - name: Upload build artifacts
#       #   uses: actions/upload-artifact@v4
#       #   with:
#       #     path: out
#       #     name: github-pages
#       - name: Deploy to GitHub Pages
#         uses: actions/deploy-pages@v4


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: github-pages
  #   steps:
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4